name: defalut

on:
  pull_request:
  push:
    branches: [main]

jobs:
  stylua:
    name: Check codestyle
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .

